// Predefined list from Bulbapedia (normalized lowercase, easy to update/extend)
export const genderDiffSpecies: string[] = [
  // Generation I
  "venusaur",
  "butterfree",
  "rattata",
  "raticate",
  "pikachu",
  "raichu",
  "zubat",
  "golbat",
  "gloom",
  "vileplume",
  "kadabra",
  "alakazam",
  "doduo",
  "dodrio",
  "hypno",
  "rhyhorn",
  "rhydon",
  "eevee",
  "goldeen",
  "seaking",
  "scyther",
  "magikarp",
  "gyarados",

  // Generation II
  "meganium",
  "ledyba",
  "ledian",
  "xatu",
  "sudowoodo",
  "politoed",
  "aipom",
  "wooper",
  "quagsire",
  "murkrow",
  "wobbuffet",
  "girafarig",
  "gligar",
  "steelix",
  "scizor",
  "heracross",
  "sneasel",
  "sneasel-hisui", // Hisuian Sneasel (PokeAPI form id)
  "ursaring",
  "piloswine",
  "octillery",
  "houndoom",
  "donphan",

  // Generation III
  "torchic",
  "combusken",
  "blaziken",
  "beautifly",
  "dustox",
  "ludicolo",
  "nuzleaf",
  "shiftry",
  "meditite",
  "medicham",
  "roselia",
  "gulpin",
  "swalot",
  "numel",
  "camerupt",
  "cacturne",
  "milotic",
  "relicanth",

  // Generation IV
  "starly",
  "staravia",
  "staraptor",
  "bidoof",
  "bibarel",
  "kricketot",
  "kricketune",
  "shinx",
  "luxio",
  "luxray",
  "roserade",
  "combee",
  "pachirisu",
  "buizel",
  "floatzel",
  "ambipom",
  "gible",
  "gabite",
  "garchomp",
  "hippopotas",
  "hippowdon",
  "croagunk",
  "toxicroak",
  "finneon",
  "lumineon",
  "snover",
  "abomasnow",
  "weavile",
  "rhyperior",
  "tangrowth",
  "mamoswine",

  // Generation V
  "unfezant",
  "frillish",
  "jellicent",

  // Generation VI
  "pyroar",
  "meowstic",

  // Generation VIII
  "indeedee",
  "basculegion",

  // Generation IX
  "oinkologne",
];